### PR TITLE
IPNS dag-cbor data

### PR DESCRIPTION
**Pull request by SionoiS**
Tested with rust and it seams to be working.

### CODE REVIEW

**Comment by rvagg** [comment]
@SionoiS as this is it won't work quite right because it's only going to test that it can decode and reencode as dag-cbor, but we want the same forms to cross different codec boundaries. You need to move this into `_fixtures_src/`, give it a nicer name (don't worry about the CID), maybe just `ipns.dag-cbor`. Then go into the `js/` directory and with Node.js installed: `npm install` and then `node make-fixtures.js`--it's in JS cause that was easiest when I set this up but what it does is take the input files, decodes them in whatever codec you named your file with, then writes out a version with each codec that will support that data model form (i.e. you won't get a dag-pb version of this coming out) and gives them the "correct" CID in the filename.
Then, by being able to load and convert the same data between codecs and testing the CIDs we can affirm that the codecs are behaving correctly for this data.

What you should expect is that you end up with a file with the same CID that you're using in this PR, if you don't then it suggests there's a codec problem with one of the implementations.

**Review by rvagg — CHANGES_REQUESTED** [review]
as per comment above

**Comment by SionoiS** [comment]
@rvagg
My thinking was that the IPNS spec ask for dag-cbor data specifically. Records will never have dag-json data so why test the interop.

Maybe someone will want to at some point. :shrug: 

Will make the changes!

**Review by rvagg — APPROVED** [review]

**Comment by rvagg** [comment]
@SionoiS the point isn't to make sure it's dag-json compatible, the reason we do it across multiple fixtures is to exercise the transformation into and out of the data model - so if the same data model form can go all the way down into dag-json, come back out and then into dag-cbor and retain the same CID then the codecs are working as expected. If this data loaded in dag-cbor, then saved as dag-json with a different CID then it would suggest a problem somewhere in that chain and not necessarily in dag-cbor. Same with the reverse, the dag-json->dag-cbor transform, which is why we do them all the ways and check CIDs at each point for stability.

Good data though! Thanks for the contribution, very helpful

**Comment by SionoiS** [comment]
@rvagg Thanks for the explanation. Make sense!

**Pull request merged**
